-- MySQL Script generated by MySQL Workbench
-- 11/27/14 23:30:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema macShop2015
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `macShop2015` ;

-- -----------------------------------------------------
-- Schema macShop2015
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `macShop2015` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `macShop2015` ;

-- -----------------------------------------------------
-- Table `macShop2015`.`CA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `macShop2015`.`CA` ;

CREATE TABLE IF NOT EXISTS `macShop2015`.`CA` (
  `idCA` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCA`),
  UNIQUE INDEX `idCA_UNIQUE` (`idCA` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `macShop2015`.`Provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `macShop2015`.`Provincia` ;

CREATE TABLE IF NOT EXISTS `macShop2015`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `CA_idCA` INT NOT NULL,
  PRIMARY KEY (`idProvincia`, `CA_idCA`),
  UNIQUE INDEX `idProvincia_UNIQUE` (`idProvincia` ASC),
  INDEX `fk_Provincia_CA1_idx` (`CA_idCA` ASC),
  CONSTRAINT `fk_Provincia_CA1`
    FOREIGN KEY (`CA_idCA`)
    REFERENCES `macShop2015`.`CA` (`idCA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `macShop2015`.`Ciudad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `macShop2015`.`Ciudad` ;

CREATE TABLE IF NOT EXISTS `macShop2015`.`Ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `Provincia_idProvincia` INT NOT NULL,
  `Provincia_CA_idCA` INT NOT NULL,
  PRIMARY KEY (`idCiudad`, `Provincia_idProvincia`, `Provincia_CA_idCA`),
  UNIQUE INDEX `idCiudad_UNIQUE` (`idCiudad` ASC),
  INDEX `fk_Ciudad_Provincia1_idx` (`Provincia_idProvincia` ASC, `Provincia_CA_idCA` ASC),
  CONSTRAINT `fk_Ciudad_Provincia1`
    FOREIGN KEY (`Provincia_idProvincia` , `Provincia_CA_idCA`)
    REFERENCES `macShop2015`.`Provincia` (`idProvincia` , `CA_idCA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `macShop2015`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `macShop2015`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `macShop2015`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  `Ciudad_Provincia_idProvincia` INT NOT NULL,
  `Ciudad_Provincia_CA_idCA` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `Ciudad_idCiudad`, `Ciudad_Provincia_idProvincia`, `Ciudad_Provincia_CA_idCA`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `pass_UNIQUE` (`pass` ASC),
  INDEX `fk_Usuario_Ciudad1_idx` (`Ciudad_idCiudad` ASC, `Ciudad_Provincia_idProvincia` ASC, `Ciudad_Provincia_CA_idCA` ASC),
  CONSTRAINT `fk_Usuario_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad` , `Ciudad_Provincia_idProvincia` , `Ciudad_Provincia_CA_idCA`)
    REFERENCES `macShop2015`.`Ciudad` (`idCiudad` , `Provincia_idProvincia` , `Provincia_CA_idCA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `macShop2015`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `macShop2015`.`Admin` ;

CREATE TABLE IF NOT EXISTS `macShop2015`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `pass` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `permiso` INT NOT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idAdmin_UNIQUE` (`idAdmin` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `macShop2015`.`Oferta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `macShop2015`.`Oferta` ;

CREATE TABLE IF NOT EXISTS `macShop2015`.`Oferta` (
  `idOferta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  `Ciudad_idCiudad` INT NOT NULL,
  `Ciudad_Provincia_idProvincia` INT NOT NULL,
  `Ciudad_Provincia_CA_idCA` INT NOT NULL,
  `Admin_idAdmin` INT NOT NULL,
  `num_ofertas` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`idOferta`, `Ciudad_idCiudad`, `Ciudad_Provincia_idProvincia`, `Ciudad_Provincia_CA_idCA`, `Admin_idAdmin`),
  UNIQUE INDEX `idOferta_UNIQUE` (`idOferta` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_Oferta_Ciudad1_idx` (`Ciudad_idCiudad` ASC, `Ciudad_Provincia_idProvincia` ASC, `Ciudad_Provincia_CA_idCA` ASC),
  INDEX `fk_Oferta_Admin1_idx` (`Admin_idAdmin` ASC),
  CONSTRAINT `fk_Oferta_Ciudad1`
    FOREIGN KEY (`Ciudad_idCiudad` , `Ciudad_Provincia_idProvincia` , `Ciudad_Provincia_CA_idCA`)
    REFERENCES `macShop2015`.`Ciudad` (`idCiudad` , `Provincia_idProvincia` , `Provincia_CA_idCA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Oferta_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `macShop2015`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `macShop2015`.`Usuario_tiene_Oferta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `macShop2015`.`Usuario_tiene_Oferta` ;

CREATE TABLE IF NOT EXISTS `macShop2015`.`Usuario_tiene_Oferta` (
  `Usuario_idUsuario` INT NOT NULL,
  `Oferta_idOferta` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Oferta_idOferta`),
  INDEX `fk_Usuario_has_Oferta_Oferta1_idx` (`Oferta_idOferta` ASC),
  INDEX `fk_Usuario_has_Oferta_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Oferta_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `macShop2015`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Oferta_Oferta1`
    FOREIGN KEY (`Oferta_idOferta`)
    REFERENCES `macShop2015`.`Oferta` (`idOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
