-- MySQL Script generated by MySQL Workbench
-- 11/26/14 21:05:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema macShop2015
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `macShop2015` ;

-- -----------------------------------------------------
-- Schema macShop2015
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `macShop2015` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `macShop2015` ;

-- -----------------------------------------------------
-- Table `macShop2015`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `macShop2015`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `macShop2015`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `pass_UNIQUE` (`pass` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `macShop2015`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `macShop2015`.`Admin` ;

CREATE TABLE IF NOT EXISTS `macShop2015`.`Admin` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `pass` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  UNIQUE INDEX `idAdmin_UNIQUE` (`idAdmin` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `macShop2015`.`Oferta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `macShop2015`.`Oferta` ;

CREATE TABLE IF NOT EXISTS `macShop2015`.`Oferta` (
  `idOferta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  `Admin_idAdmin` INT NOT NULL,
  PRIMARY KEY (`idOferta`),
  UNIQUE INDEX `idOferta_UNIQUE` (`idOferta` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_Oferta_Admin1_idx` (`Admin_idAdmin` ASC),
  CONSTRAINT `fk_Oferta_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `macShop2015`.`Admin` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `macShop2015`.`Usuario_tiene_Oferta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `macShop2015`.`Usuario_tiene_Oferta` ;

CREATE TABLE IF NOT EXISTS `macShop2015`.`Usuario_tiene_Oferta` (
  `Usuario_idUsuario` INT NOT NULL,
  `Oferta_idOferta` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Oferta_idOferta`),
  INDEX `fk_Usuario_has_Oferta_Oferta1_idx` (`Oferta_idOferta` ASC),
  INDEX `fk_Usuario_has_Oferta_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Oferta_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `macShop2015`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Oferta_Oferta1`
    FOREIGN KEY (`Oferta_idOferta`)
    REFERENCES `macShop2015`.`Oferta` (`idOferta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
